### ISSUE TITLE
LiveUpdate todo

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#300]
- [x] use tk.after() for delay live update on text entry
- [x]  Don’t update other dataset combo boxes when a description_column, if row is virtual
- [x]  Create new Relationship function that returns data_key : column of all dependent columns (that are foreign keyed to the updated column, but arnt cascade dependent.
- [x]  And another uses above to see if the description column used in dependent so.Table TableHeadings col list
