### ISSUE TITLE
TODO: More performant LiveUpdate

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#315]
- [ ] add a requery_current, that only refetches current_row and reinserts into DataSet.rows
- [ ] add current_row_only=True/False & column_name to update_selectors. This would use direct tkinter-calls to change the row/column of a sg.Table, like we do in CellEdit.
- [ ] using same method as above, support direct inserting/deleting from a sg.Table without rebuilding the entire table.

**Comment by ssweber** [comment]
After rewriting table_values, now I’m less concerned about this.
