### ISSUE TITLE
Meta Issue

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#38]
Thank you so much for get all those changes and fixes in there! My activity will slow down as well; master now resolves all outstanding issues for my work project! It's been educational to work on this project... I hope my convoluted attempts at fixing things didn't side-track you from the true solutions too much.

Going forward I'll list bug/enhancements/code style below, and when I get time flesh them out in a linked issue. If you approve (and they are simple enough), I'll create on my branch and do a pull-request one-at-a-time.

Code:
- [x] ~~[Reduce setters, getters for variables - reducing function proliferation.](https://github.com/PySimpleSQL/pysimplesql/issues/39)~~
- [x] ~~[Switch AllKeysDict to key_dict](https://github.com/PySimpleSQL/pysimplesql/issues/40)~~
- [ ] One-time Black reformat, with black on commit.
- [x] [Merge saving behavior](https://github.com/PySimpleSQL/pysimplesql/issues/71)

Features:
- [x] Popup for sqlite errors (try/except) - eg for Not Null and Unique columns
- [x] Localization/customization of msg 
- [x] ~~[Search - move scrollbar down to highlighted element.](https://github.com/PySimpleSQL/pysimplesql/issues/55)~~
- [x] [Temp/Virtual row for Insert w/ validators?](https://github.com/PySimpleSQL/pysimplesql/issues/70)
- [x] [Popup for duplicate, this record only, or it and children](https://github.com/PySimpleSQL/pysimplesql/issues/73)
- [ ] Popup for child-reparenting. Stay on current parent, or go with this record? Will need a requery_on_cascade_fk_change = False added to Query.

Bugs/Document Behavior:
- [x] #89 
- [x] [Child reparenting](https://github.com/PySimpleSQL/pysimplesql/pull/64/commits/abaf927a8fee8e666511198d7ab1d464ade17693)
- [x] [Display none if parent not selected](https://github.com/PySimpleSQL/pysimplesql/issues/60)
- [x] [Disallowed table/column names](https://github.com/PySimpleSQL/pysimplesql/issues/72)
- [x] fixed with virtual rows. Cannot set column as Not Null without a default value

Documentation Improvements
- [ ] edit_protect=False on 1 ss.action will turn off edit_protect.
- [ ] [SUPPORTED] - Make it clear on tutorial doc that quick_editor = False changes ss.records so that they wont all have edit buttons next to them. Update Images to show quick_editor button.
- [x] How to edit_protect a sg.CalendarButton
- [ ] Generate Call Reference
- [x] Add docstrings for selector function
- [ ] New mega boiler-plate example, with tabs, nested tabs, prompt save and save on exit, etc.

Python version support
- [x] Test for version support. Current dict union '|' in load_iconpack is 3.9

**Comment by PySimpleSQL** [comment]
Thanks again for the great help in fleshing out those issues.  Sorry if at times I had to discard your hard work - the creativity of how you handled the same things was awesome to see (especially not being too familiar with the code base) - there were just a lot of opportunities to reduce bloat by using features that were already present with very minimal changes.  In the end, the project feels much more complete already!

I agree with pretty much everything you have to say up above - I'm from the line of thought "First get it working, then optimize and improve". I feel like the base code is working great and it's a perfect time to start the next phase of cleanup and optimization.

I have a comments one of the items you listed above:

> If Parent A is selected, cannot change to different Parent (eg B) on Child record.
Yes, this is a current limitation, as at the Query level only one record can be selected at a time.  The way to handle this is to just create another Form which has it's own Queries and therefore can have independent selection. It was a design feature that was considered very early on as a trade-off for control and ease of use. I definitely need to make an example for this case - not only to show its use but to identify areas for improvement (like built-in glue code to tie the forms together in a sense)

One of my long term goals coming up is to abstract the database interactions so that MySql, Postgre etc. can be used as a backed as easily as SQLite3.

If you don't mind, I may pick away at some of these issues as well.  I'll be sure to reference this ticket if I do to avoid duplication of efforts

**Comment by ssweber** [comment]
pretty much took care of this, closing.
